defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome69
  environment:
    TZ: "Asia/Yekaterinburg"

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0

jobs:
  prepare:
    <<: *defaults

    steps:
      - checkout

      # find compatible cache from previous build,
      # it should have same dependencies installed from package.json checksum
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-

      # install dependencies from package-lock.json
      - run: npm ci

      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache

      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress

#      - store_test_results:
#          path: test-reports
#
#      - store_artifacts:
#          path: test-reports

#workflows:
#  version: 2
#  test_build_app:
#    jobs:
#      - unit_tests
#      - e2e_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - prepare
      - cypress/run:
          requires:
            - prepare
          start: 'npm run serve'

